Added the ability to forget networks with this script.

diff --git a/get-wifi-password b/get-wifi-password
--- a/get-wifi-password
+++ b/get-wifi-password
@@ -59,11 +59,36 @@ elif [ "$1" == "-h" ]; then
   echo ""
   echo "use the -ls argument to get a list of SSIDs that you can use"
   echo ""
+  echo "use the -rm argument to forget a network."
   echo ""
   echo "Examples:"
   echo ""
   echo "    $ get-wifi-password my_wifi"
   echo "    my very complicated password"
+  echo ""
+  echo "    $ get-wifi-password -rm my_wifi"
+
+# Forget a network
+elif [ "$1" == "-rm" ]; then
+  ssid="$@"
+  ssid=${ssid:4}
+
+  echo "Forgetting the network..."
+  sudo rm -rf "$ssid"
+  if [ $? -ne 0 ]; then
+    echo "Could not forget network. Maybe there was a typo."
+    exit 1
+  fi
+
+  echo "Restarting the network-manager service..."
+  sudo service network-manager restart
+  if [ $? -ne 0 ]; then
+    echo "Failed to restart the network-manager. The changes may not take"
+    echo "effect until it is restarted or, there is a system reboot."
+    exit 1
+  fi
+
+  echo "Success!"
 
 # check $1 and get the wifi password for that network
 else
